apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: pfe
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
 
    scrape_configs:
 
      - job_name: 'api-2d'
        static_configs:
          - targets: ['api-2d-service:8000']
        metrics_path: /metrics
 
      - job_name: 'worker-2d'
        static_configs:
          - targets: ['worker-2d-service:8080']
        metrics_path: /metrics
 
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
 
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics:8080']
 
      - job_name: 'postgres'
        static_configs:
          - targets: ['postgres-exporter:9187']
