database:
  host: "db.example.com"
  port: 5432
  name: "anomaly_detection"
  user: "admin"
  pass: "password"

paths:
  images_root: "/home/mario/database-pfe"

network:
  images_url: "http://images.example.com"
