apiVersion: v1
kind: Service
metadata:
  name: worker-2d-service
  namespace: pfe
  labels:
    app: worker-2d
spec:
  selector:
    app: worker-2d
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
